######################## default configuration ####################
baseURL = "https://finteh.org"
title = "finteh | non-governmental organization"
theme = "fintehsitev2"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "finteh" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["fr"] # desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
#[[params.plugins.css]]
#link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/fontawesome/css/all.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "NGO finteh"
author = "Themefisher"
# contact info
address = "Tadeusza Kościuszki 10, 05-500 Warsaw, Poland"
mobile = "+48 515 083 616"
email = "inbox@finteh.org"
# contact form action
contact_form_action = "https://formspree.io/f/xpzrgzjb" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-88015393-6" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://finteh.us21.list-manage.com/subscribe/post?u=e7f9e0dbf7ea8ebde101e4b3c&amp;id=6c2abff8be&amp;f_id=001a88e1f0" # replace this url with yours
mailchimp_form_name = "b_e7f9e0dbf7ea8ebde101e4b3c_6c2abff8be" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "52.07380536671752"
map_longitude = "21.027064677911692"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 30
  
############################# social site ########################

[[params.social]]
title = "telegram"
icon = "fa-brands fa-telegram" # themify icon : https://themify.me/themify-icons
link = "https://t.me/finteh"

[[params.social]]
title = "twitter"
icon = "fa-brands fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/finteh"

[[params.social]]
title = "github"
icon = "fa-brands fa-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/finteh"

[[params.social]]
title = "linkedin"
icon = "fa-brands fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://linkedin.com/company/finteh"



################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "content CC BY 4.0 | theme © by [Themefisher](https://themefisher.com/hugo-themes/)"



################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1

[[Languages.en.menu.main]]
name = "services"
url = "service/"
weight = 2

[[Languages.en.menu.main]]
name = "incubator"
url = "incubator/"
weight = 3

[[Languages.en.menu.main]]
name = "nodes"
url = "nodes/"
weight = 4

[[Languages.en.menu.main]]
weight = 5
name = "Pages"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "Board and experts pool"
  url = "expert/"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "event"
  url = "event/"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "documentation"
  url = "documentation/"
 
#  [[Languages.en.menu.main]]
#  parent = "Pages"
#  name = "research"
#  url = "research/"
  
#[[Languages.en.menu.main]]
#name = "blog"
#url = "blog/"
#weight = 4
  
[[Languages.en.menu.main]]
name = "Contact"
url = "contact/"
weight = 6


# footer menu

[[Languages.en.menu.footer]]
name = "Board and experts pool"
url = "expert/"

[[Languages.en.menu.footer]]
name = "documentation"
url = "documentation/"

[[Languages.en.menu.footer]]
name = "event"
url = "event/"

[[Languages.en.menu.footer]]
name = "nodes"
url = "nodes/"

#[[Languages.en.menu.footer]]
#name = "scholarship"
#url = "scholarship/"

#[[Languages.en.menu.footer]]
#name = "research"
#url = "research/"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# copyright
copyright = "Copyright &copy; 2021 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"




